name: CI
on:
  push:
    branches: [ "master", "component-lib" ]
  workflow_dispatch:

jobs:
  NPM:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Dependencies
        run: npm ci

      - name: Increase version
        run: npm version patch

      - name: Build
        run: npm run build-lib

      - name: Save version
        id: version
        run: echo ::set-output name=tag::$(echo $(node -p -e "require('./package.json').version"))

      - name: Push new version
        run: git push